version: '3.8'
services:
  web:
    image: rainbunny/auth-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '3001:3000'
    volumes:
      - .:/app
